// <auto-generated />
using System.Collections.Generic;
using AStar.Dev.CloudSyncFunctional.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AStar.Dev.CloudSyncFunctional.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527085721_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("AStar.Dev.CloudSyncFunctional.Persistence.Entities.AccountEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriveId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastSyncedAt")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Profile", "AStar.Dev.CloudSyncFunctional.Persistence.Entities.AccountEntity.Profile#AccountProfileEntity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("DisplayName");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Email");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SyncConfig", "AStar.Dev.CloudSyncFunctional.Persistence.Entities.AccountEntity.SyncConfig#AccountSyncConfig", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("LocalSyncPath")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("LocalSyncPath");

                            b1.Property<int>("WorkerCount")
                                .HasColumnType("INTEGER")
                                .HasColumnName("WorkerCount");
                        });

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AStar.Dev.CloudSyncFunctional.Persistence.Entities.DriveStateEntity", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeltaLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastCheckedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId");

                    b.ToTable("DriveStates");
                });

            modelBuilder.Entity("AStar.Dev.CloudSyncFunctional.Persistence.Entities.FileClassificationRuleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FileClassificationRules");
                });

            modelBuilder.Entity("AStar.Dev.CloudSyncFunctional.Persistence.Entities.SyncConflictEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LocalModifiedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RemoteItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RemoteModifiedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("SyncConflicts");
                });

            modelBuilder.Entity("AStar.Dev.CloudSyncFunctional.Persistence.Entities.SyncJobEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemotePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("SyncJobs");
                });

            modelBuilder.Entity("AStar.Dev.CloudSyncFunctional.Persistence.Entities.SyncRuleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemotePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RuleType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("SyncRules");
                });

            modelBuilder.Entity("AStar.Dev.CloudSyncFunctional.Persistence.Entities.SyncedItemClassificationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncedItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SyncedItemId");

                    b.ToTable("SyncedItemClassifications");
                });

            modelBuilder.Entity("AStar.Dev.CloudSyncFunctional.Persistence.Entities.SyncedItemEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ETag")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RemoteModifiedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RemotePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("SyncedItems");
                });

            modelBuilder.Entity("AStar.Dev.CloudSyncFunctional.Persistence.Entities.DriveStateEntity", b =>
                {
                    b.HasOne("AStar.Dev.CloudSyncFunctional.Persistence.Entities.AccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AStar.Dev.CloudSyncFunctional.Persistence.Entities.SyncConflictEntity", b =>
                {
                    b.HasOne("AStar.Dev.CloudSyncFunctional.Persistence.Entities.AccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AStar.Dev.CloudSyncFunctional.Persistence.Entities.SyncJobEntity", b =>
                {
                    b.HasOne("AStar.Dev.CloudSyncFunctional.Persistence.Entities.AccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AStar.Dev.CloudSyncFunctional.Persistence.Entities.SyncRuleEntity", b =>
                {
                    b.HasOne("AStar.Dev.CloudSyncFunctional.Persistence.Entities.AccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AStar.Dev.CloudSyncFunctional.Persistence.Entities.SyncedItemClassificationEntity", b =>
                {
                    b.HasOne("AStar.Dev.CloudSyncFunctional.Persistence.Entities.SyncedItemEntity", null)
                        .WithMany()
                        .HasForeignKey("SyncedItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AStar.Dev.CloudSyncFunctional.Persistence.Entities.SyncedItemEntity", b =>
                {
                    b.HasOne("AStar.Dev.CloudSyncFunctional.Persistence.Entities.AccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
